//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KargoTrackingSystems
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kargolar
    {
        public int Id { get; set; }
        public string KargoAdi { get; set; }
        public string KargoTakipNumarasi { get; set; }
        public string KargoAciklamasi { get; set; }
    }
}
